/demo_Node2:
  ros__parameters:
    background_b: 100
    background_g: 50
    background_r: 0
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 500
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false
